#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-get
set -e
portz_root=${portz_libdir-`pwd`}

package=$1

. ${portz_root}/scripts/defs.sh
portz_assert_know_package

archive_file=$(portz_step $(pwd) fetch ${baseurl})
inform archive_file="$archive_file"
portz_step src/${package} unarchive ${archive_file}
