#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-dist
export PNAME

set -e 
#set -x
portz_root=${portz_libdir-`pwd`}

package=$1

. ${portz_root}/scripts/defs.sh
portz_assert_know_package

inform "prefix      = $prefix"
inform "exec_prefix = $exec_prefix"

. ${portz_scripts}/install_staging.sh

portz_step $(pwd) dist


# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

