#!/bin/sh
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=`basename $0`
set -e
portz_root=`dirname $0`
portz_root=$PWD

. ${portz_root}/portz_common.sh

inform "prefix      = $prefix"
inform "exec_prefix = $exec_prefix"

#set -x

if [ "$1" = "--update" ] ; then
    inform "updating repository"
    exit 0
elif [ "$1" = "--install" ] ; then
    shift
else
    #fail "bad usage"
    #exit 1
    :
fi

packages=$*

while [ -n "$packages" ] ; do
    for package in $packages ; do
        inform "trying $package ..."
        if portz_is_installed $package ; then
            inform "already installed"
        elif portz_check_deps $package ; then
            portz_install $package        
        else
            failed_deps="$failed_deps $package"
        fi
    done
    packages="$failed_deps"
done
