#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz_invoke
export PNAME

set -e 
#set -x
portz_root=$(pwd)


package_param=$1
shift
. ${portz_root}/scripts/defs.sh
portz_assert_know_package

inform "prefix      = $prefix"
inform "exec_prefix = $exec_prefix"

# find dirs

src_dir=$(portz_step ${TMP}/portz/${package}/src find_src_dir)
inform src_dir="$src_dir"

bld_dir=$(portz_step ${src_dir} find_bld_dir)
inform bld_dir="$bld_dir"

maybe_detect_stereotype

while [ -n "$1" ] ; do

    action=$1

    case "$action" in
        fetch_src):
            . ${portz_root}/scripts/fetch_src.sh
            ;;
        build|configure|install_staging)
            portz_step ${bld_dir} $action
            ;;
        patch|patch_after_conf)
            portz_step ${src_dir} $action
            ;;
        dist)
            portz_step $(pwd) $action
            ;;
        deploy|make_manifest|make_pkginfo)
            portz_step ${staging_dir} $action
            ;;
        *)
            fail "this action can't be run from $0"
            ;;
    esac
    shift
done

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

