#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz_install
export PNAME

set -e 
portz_root=$(pwd)
export portz_root
package_param=$1

build_command="$0 $@"
export build_command

. ${portz_root}/scripts/defs.sh

portz_assert_know_package

inform "prefix      = $prefix"
inform "exec_prefix = $exec_prefix"

. ${portz_scripts}/install_staging.sh

portz_step ${staging_dir} deploy



