#!/usr/bin/env bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-install
export PNAME

set -e
#set -x

portz_libdir=${portz_libdir-`pwd`}
. ${portz_libdir}/scripts/runtime.sh
. ${portz_scripts}/functions.sh
#. ${portz_scripts}/build_defs.sh
. ${portz_scripts}/package_defs.sh

install_dependencies()
{
    if [ -n "$depends" ] ; then 
        inform "DEPENDS: $depends"
    
        for dep in $depends ; do
            if portz_check_installed $dep ; then
                inform "dependency '$dep' already installed"
            else
                inform "dependency '$dep' not met, installing"
                (
                    $0 $dep
                )
                r=$?
                if [ "$r" != 0 ] ; then
                    overall_result=$r
                    failed_packages="$failed_packages $dep"
                else
                    successfull_installs="$successfull_installs $dep"
                fi
            fi
        done
    fi
}

overall_result=0
for p in $* ; do
    (
        load_package $p
        
        PNAME="$PNAME[$package_name]"
        SCRIPT_NAME="$PNAME"

        install_dependencies
        
        log_quiet=1
        . ${portz_scripts}/build_defs.sh
        log_quiet=0
        
        setup_package_build_defs

        build_command="$0 $package_path"
        export build_command
        
        . ${portz_scripts}/install_staging.sh

        portz_step ${staging_dir} deploy
    )
    r=$?
    if [ "$r" != 0 ] ; then
        overall_result=$r
        failed_packages="$failed_packages $p"
    else
        successfull_installs="$successfull_installs $p"
    fi
done

if [ -n "$successfull_installs" ]; then
    log_info "successfully installed: $successfull_installs"
fi
if [ "$overall_result" != 0 ] ; then
    log_info "failure, following packages failed to install: $failed_packages"
fi
exit $overall_result

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

