#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-invoke
export PNAME

set -e 
#set -x

portz_libdir=${portz_libdir-`pwd`}
. ${portz_libdir}/scripts/runtime.sh
. ${portz_scripts}/functions.sh
. ${portz_scripts}/build_defs.sh
. ${portz_scripts}/package_defs.sh

load_package $1
shift

build_command="$0 $package_path"
export build_command

PNAME="$PNAME[$package_name]"
SCRIPT_NAME="$PNAME"

src_dir=$(portz_step ${TMP}/portz/${package_name}/src find_src_dir)
inform src_dir="$src_dir"

bld_dir=$(portz_step ${src_dir} find_bld_dir)
inform bld_dir="$bld_dir"

maybe_detect_stereotype
setup_package_build_defs

while [ -n "$1" ] ; do

    action=$1

    case "$action" in
        fetch_src):
            . ${portz_scripts}/fetch_src.sh
            ;;
        build|configure|install_staging)
            portz_step ${bld_dir} $action
            ;;
        patch|patch_after_conf)
            portz_step ${src_dir} $action
            ;;
        dist)
            portz_step $(pwd) $action
            ;;
        deploy|make_manifest|make_pkginfo)
            portz_step ${staging_dir} $action
            ;;
        *)
            fail "unknown action '$action'"
            ;;
    esac
    shift
done

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

