#!/bin/sh
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=`basename $0`
set -e
portz_root=$PWD

. ${portz_root}/portz_common.sh

url=$1

inform "fertching source from source url: $baseurl"
archive=`portz_need_source $url`
inform "got archive: $archive"
tmpsrcdir=$PWD/src/$package
mkdir -p $tmpsrcdir
(
    cd $tmpsrcdir
    inform unpacking to $PWD
    portz_unarchive $archive 
)
