#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-uninstall
set -e
portz_root=${portz_libdir-`pwd`}

package=$1

. ${portz_root}/scripts/defs.sh
if [ -z ${package} ] ; then
    fail "need package name"
fi
if [ ! -f ${manifest_file} ] ; then
    fail "package '$package' not installed (failed to read ${manifest_file})"
fi

XXX=/tmp/XXX
cp ${manifest_file} $XXX
(cd $prefix ; cat $XXX | xargs -n 20 rm -rvf ;)
rm $XXX

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

