#!/bin/bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-dist
export PNAME

set -e 
#set -x
portz_libdir=${portz_libdir-`pwd`}
. ${portz_libdir}/scripts/runtime.sh
. ${portz_scripts}/functions.sh
. ${portz_scripts}/build_defs.sh
. ${portz_scripts}/package_defs.sh

load_package $1
package_setup_variables

build_command="$0 $package_path"
export build_command

PNAME="$PNAME[$package_name]"
SCRIPT_NAME="$PNAME"

. ${portz_scripts}/install_staging.sh

portz_step $(pwd) dist


# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

