#!/usr/bin/env bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-query
set -e

portz_libdir=${portz_libdir-`pwd`}
. ${portz_libdir}/scripts/runtime.sh
. ${portz_scripts}/functions.sh
log_quiet=1
. ${portz_scripts}/build_defs.sh
log_quiet=0
. ${portz_scripts}/package_defs.sh

action=$1
package_name=$2

if [ "$action" = "list" ] ; then
    ls -1 ${exec_prefix}/lib/portz/ | grep -v PKGINFO | sed -e 's@.MANIFEST@@'
elif [ "$action" = "files" ] ; then
    package_name=$2
    if [ -z ${package_name} ] ; then
        fail "need package name"
    fi
    setup_package_build_defs

    if [ ! -f ${manifest_file} ] ; then
        fail "package '$package' not installed (failed to read ${manifest_file})"
    fi

    portz_list_files_from_manifest ${manifest_file}
else
    fail "bad usage"
fi

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

