#!/usr/bin/env bash
#
# This file is part of 'portz'
#
# Copyright (C) Zbigniew Zagorski <z.zagorski@gmail.com> and others, 
# licensed to the public under the terms of the GNU GPL (>= 2)
# see the file COPYING for details
#
# I.e., do what you like, but keep copyright and there's NO WARRANTY. 
# 

PNAME=portz-uninstall
set -e
portz_libdir=${portz_libdir-`pwd`}
. ${portz_libdir}/scripts/runtime.sh
. ${portz_scripts}/functions.sh
log_quiet=1
. ${portz_scripts}/build_defs.sh
log_quiet=0
. ${portz_scripts}/package_defs.sh

package_name=$1

if [ -z ${package_name} ] ; then
    fail "need package name"
fi

setup_package_build_defs

if [ ! -f ${manifest_file} ] ; then
    fail "package '$package_name' not installed (failed to read ${manifest_file})"
fi

XXX=/tmp/XXX
cp ${manifest_file} $XXX
(cd $prefix ; cat $XXX | xargs -n 20 rm -rvf ;)
if [ -f "$prefix/lib/portz/$package_name.PKGINFO" ] ; then
    rm -v "$prefix/lib/portz/$package_name.PKGINFO"
fi
rm $XXX

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

