#!/bin/bash

. ${portz_root}/scripts/defs.sh

#
# this is default script for deploying package from temporary staging area (${staging_dir})
# to its final location (prefix and exec_prefix)

# TODO, invent more intelligent way of
# moving whole directory tree

if [ ! -d $prefix ] ; then
	mkdir $prefix
fi

if [ ! -w $prefix ] ; then
	echo "$PNAME: must escalate priviledges to root"
	MAYBE_SUDO=sudo
fi

TAR_FLAGS="--no-overwrite-dir --atime-preserve -m --no-same-owner --no-same-permissions"
(cd ${staging_dir} ; portz_invoke ${TAR} c . ; ) | ( cd / ; portz_invoke ${MAYBE_SUDO} ${TAR} xv ${TAR_FLAGS}; )


