#!/bin/bash

#
# this is default script for deploying package from temporary staging area (${staging_dir})
# to its final location (prefix and exec_prefix)

# TODO, invent more intelligent way of
# moving whole directory tree

if [ ! -d $prefix ] ; then
	mkdir -p $prefix
fi

if [ ! -w $prefix ] ; then
    MAYBE_SUDO=${SUDO-sudo}
    inform "must escalate priviledges to root (using $MAYBE_SUDO)"
fi

gnu_tar_deploy()
{
    TAR_FLAGS="--no-overwrite-dir --atime-preserve -m --no-same-owner --no-same-permissions"
    (
        cd ${staging_dir}
        ${TAR} c .
    ) | ( 
        cd / 
        portz_invoke ${MAYBE_SUDO} ${TAR} xv ${TAR_FLAGS} 
    )
}

freebsd_cp_deploy()
{
    (
        cd ${staging_dir}
        # verbose, recursive cp with, no overwrite existing
        portz_invoke cp -f -v -R -n * /
    )
}

bsd_tar_deploy()
{
    (
        cd ${staging_dir}
        tar -cf - .
    ) | (
        cd /
        portz_invoke ${MAYBE_SUDO} tar -xpmvf -
    )
}

case "$OSTYPE" in
*darwin*)
    bsd_tar_deploy
    ;;
*freebsd*|*FreeBSD*)
    freebsd_cp_deploy
    ;;
*linux*|*Linux*)
    gnu_tar_deploy
    ;;
*)
    if [ -f gtar ] ; then
        TAR=gtar
    fi
    gnu_tar_deploy
    ;;
esac

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:


