#!/bin/bash

#
# this scripts creates binary distribution package (tar.gz) with
# compiled package
#

here=$(pwd)

portz_dist_suffix="${portz_dist_suffix-$dist_suffix}"

filename=${package_name}-${package_version}${portz_dist_suffix}.tar.gz

inform "creating distribution archive: ${filename} ($(cat ${staging_dir}${manifest_file} | wc -l ) files)"

( cd ${staging_dir}/${prefix} ; portz_invoke tar chozf ${here}/${filename} * ; )

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

