#!/bin/bash

portz_download()
{
    if which wget > /dev/null; then
        portz_invoke_always wget --no-check-certificate -O $1 $2
    elif which curl > /dev/null ; then
        portz_invoke_always curl --location --output $1 $2
    else
        inform "using bundled wget"
        portz_invoke_always ${portz_tools}/wget/wget -O $1 $*
    fi
}

url=$1
shift
filename=`basename $url`
archived_filename="${portz_archive}/$filename"

if [ ! -f $archived_filename ] ; then
    [ -d $portz_archive ] || mkdir -p $portz_archive
    #trap "rm -rf $archived_filename; exit 1"
    rm -rf $archived_filename.tmp
    portz_download ${archived_filename}.tmp $url
    mv $archived_filename.tmp $archived_filename
    #trap
fi
echo $archived_filename

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

