#!/bin/bash

if [ `ls -1 | grep -v -e "-portz-orig" | wc -l` = "1" ] ; then 
    cd `ls -1 | grep -v -e "-portz-orig"`
else
    fail "unable to find source directory in unpacked archive, override find_src_dir_step() in package def"
fi

pwd

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

