#!/bin/bash

if [ `ls -1 | wc -l` = "1" ] ; then 
    cd `ls -1`
else
    fail "unable to find source directory in unpacked archive, override goto_srcdir() in package def"
fi

pwd

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

