#!/bin/bash

inform "creating manifest file"
manifest_dir=$(dirname $manifest_file)
mkdir -p ${staging_dir}${manifest_dir}

(
    cd ${staging_dir}
    touch ${staging_dir}${manifest_file} #ensure file is on place before find starts
    find . -type f | sed -e "sX^\.${prefix}/XX" > ${staging_dir}${manifest_file}
)


inform "package ${package_name}-${package_version} installation consists of $(wc -l < ${staging_dir}${manifest_file}) files"


# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

