#!/bin/bash

#
# this script unarchives package to some current directory
#
. ${portz_root}/scripts/defs.sh

portz_unzip()
{
    if which unzip > /dev/null; then
        portz_invoke_always unzip $*
    else
        inform "using bundled unzip"
        portz_invoke_always $portz_tools/unzip/unzip $*
    fi
} 

TAR_COMMON_OPTIONS="--no-overwrite-dir --atime-preserve -m --no-same-owner --no-same-permissions"
name=${1}
case $name in
    *.tar)     portz_invoke_always ${TAR} x ${TAR_COMMON_OPTIONS} -f $name ;;
    *.tar.gz)  portz_invoke_always ${TAR} zx ${TAR_COMMON_OPTIONS} -f $name ;; 
    *.tgz)     portz_invoke_always ${TAR} zx ${TAR_COMMON_OPTIONS} -f $name ;; 
    *.tar.bz2) portz_invoke_always ${TAR} jx ${TAR_COMMON_OPTIONS} -f $name ;;
    *.tbz)     portz_invoke_always ${TAR} jx ${TAR_COMMON_OPTIONS} -f $name ;;
    *.zip)     portz_unzip $name ;;
    *.tar.lzma) portz_invoke_always ${TAR} x --lzma -f $name ;;
    # TODO, add lzma
    *) fail "unknown archive type: $name (supported tar (gz,bz2) and zip"
esac

