#!/bin/bash

#
# unarchive step accepts list of archive files
# as arguments used as:
#  portz_step ${parent_src_dir} unarchive ${archive_files}
#
#
# portz_unarchive (defined in functions.sh) is common thing that can
# unarchive common formats like zip,tgz,tbz,txz etc ...

for archive_file in $* ; do
    portz_unarchive "$archive_file"
done

# jedit: :tabSize=8:indentSize=4:noTabs=true:mode=shellscript:

